# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/' # Location of package manifests
    schedule:
      interval: 'weekly'
    cooldown:
      default-days: 7
    open-pull-requests-limit: 10
    groups:
      commitlint:
        patterns:
          - '@commitlint/cli'
          - '@commitlint/config-conventional'
          - '@commitlint/cz-commitlint'
      jest:
        patterns:
          - 'jest'
          - 'jest-each'
          - 'jest-environment-jsdom'
          - '@types/jest'
      prisma:
        patterns:
          - 'prisma'
          - '@prisma/*'
      webpack:
        patterns:
          - 'webpack'
          - 'webpack-*'
    rebase-strategy: 'disabled'
  - package-ecosystem: 'terraform'
    directory: '/infrastructure' # Location of package manifests
    schedule:
      interval: 'weekly'
      day: 'tuesday' # day after npm updates
    cooldown:
      default-days: 7
