parameters:
  - name: rollbackAPI
    displayName: Rollback the Appeals FO API
    type: boolean
    default: false
  - name: rollbackAuthServer
    displayName: Rollback the Appeals FO Auth Server
    type: boolean
    default: false
  - name: rollbackDocumentsApi
    displayName: Rollback the Appeals FO Documents Service API
    type: boolean
    default: false
  - name: rollbackPdfApi
    displayName: Rollback the Appeals FO PDF Service API
    type: boolean
    default: false
  - name: rollbackWeb
    displayName: Rollback the Appeals FO web app
    type: boolean
    default: false
  - name: region
    displayName: Region
    type: string
    values:
      - UK West
      - UK South
    default: UK West

pr: none
trigger: none

resources:
  repositories:
    - repository: templates
      type: github
      endpoint: Planning-Inspectorate
      name: Planning-Inspectorate/common-pipeline-templates
      ref: refs/tags/release/3.24.2
extends:
  template: stages/wrapper_cd.yml@templates
  parameters:
    variableGroupPrefix: 'cd'
    environments:
      - name: Dev
      - name: Test
        dependsOn:
          - Dev
      - name: Training
        dependsOn:
          - Test
      - name: Prod
        dependsOn:
          - Training
    globalVariables:
      - template: .azure/pipelines/azure-pipelines-variables.yml@self
    deploymentStages:
      - name: Rollback
        deploymentJobs:
          - name: Rollback Web API
            condition: ${{ eq(parameters.rollbackAPI, true) }}
            steps:
              - template: ../steps/azure_web_app_slot_swap.yml
                parameters:
                  appName: pins-app-appeals-service-appeals-api-$(ENVIRONMENT)-$(REGION_SHORT)-001
                  appResourceGroup: $(resourceGroup)
                  appStagingSlotName: staging
                  appTargetSlotName: production
          - name: Rollback Auth Server
            condition: ${{ eq(parameters.rollbackAuthServer, true) }}
            steps:
              - template: ../steps/azure_web_app_slot_swap.yml
                parameters:
                  appName: pins-app-appeals-service-auth-server-$(ENVIRONMENT)-$(REGION_SHORT)-001
                  appResourceGroup: $(resourceGroup)
                  appStagingSlotName: staging
                  appTargetSlotName: production
          - name: Rollback Documents API
            condition: ${{ eq(parameters.rollbackDocumentsApi, true) }}
            steps:
              - template: ../steps/azure_web_app_slot_swap.yml
                parameters:
                  appName: pins-app-appeals-service-documents-api-$(ENVIRONMENT)-$(REGION_SHORT)-001
                  appResourceGroup: $(resourceGroup)
                  appStagingSlotName: staging
                  appTargetSlotName: production
          - name: Rollback PDF API
            condition: ${{ eq(parameters.rollbackPdfApi, true) }}
            steps:
              - template: ../steps/azure_web_app_slot_swap.yml
                parameters:
                  appName: pins-app-appeals-service-pdf-api-$(ENVIRONMENT)-$(REGION_SHORT)-001
                  appResourceGroup: $(resourceGroup)
                  appStagingSlotName: staging
                  appTargetSlotName: production
          - name: Rollback Web App
            condition: ${{ eq(parameters.rollbackWeb, true) }}
            steps:
              - template: ../steps/azure_web_app_slot_swap.yml
                parameters:
                  appName: pins-app-appeals-service-appeals-wfe-$(ENVIRONMENT)-$(REGION_SHORT)-001
                  appResourceGroup: $(resourceGroup)
                  appStagingSlotName: staging
                  appTargetSlotName: production
