apiVersion: v2
name: app
description: PINS Appeal Process
type: application
version: 0.1.0
icon: https://github.com/planning-inspectorate.png
dependencies:
  - name: openfaas-amqp1-0-connector
    alias: horizon-householder-appeal-publish
    version: ^1.0.0
    repository: file://../openfaas-amqp1.0-connector
