apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-response-headers
data:
  Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-inline' https://www.googletagmanager.com; img-src www.googletagmanager.com;
  Permissions-Policy: vibrate=(), camera=(), microphone=(), geolocation=(), autoplay=()
  Referrer-Policy: strict-origin
  X-Content-Type-Options: nosniff
  X-Frame-Options: SAMEORIGIN
