trigger:
  paths:
    include:
      - packages/pdf-service-api

pr:
  branches:
    include:
      - main
  paths:
    include:
      - packages/pdf-service-api

resources:
  repositories:
    - repository: templates
      type: github
      endpoint: Planning-Inspectorate
      name: Planning-Inspectorate/common-pipeline-templates
      ref: refs/tags/release/2.1.1

extends:
  template: stages/wrapper_ci.yml@templates
  parameters:
    globalVariables:
      - template: azure-pipelines-variables.yml@self
      - template: packages/pdf-service-api/pipelines/azure-pipelines-variables.yml@self
    validateName: Build Test and Push
    validationSteps:
      - script: |
          buildName=$(versionNumber)_$(Build.BuildId)
          echo "Setting the name of the build to '$buildName'."
          echo "##vso[build.updatebuildnumber]$buildName"
        displayName: Set Build Number
      - template: steps/azure_web_app_acr_push.yml@templates
        parameters:
          azurecrName: $(azurecrName)
          dockerfilePath: $(dockerFilePath)
          repository: $(repository)
          runTests: true
          testRunTitle: PDF Service API Jest Tests
          workingDirectory: $(Build.Repository.LocalPath)
