apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.fullname" . }}-form-web-app
  labels:
  {{- include "app.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.formsWebApp.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
  {{- include "app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: {{ .Values.formsWebApp.config.port | quote }}
        {{- with .Values.podAnnotations }}
      {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
    {{- include "app.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "app.serviceAccountName" . }}
      securityContext:
      {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.formsWebApp.image.repository }}:{{ .Values.formsWebApp.image.tag }}"
          imagePullPolicy: {{ .Values.formsWebApp.image.pullPolicy }}
          ports:
            - name: {{.Values.formsWebApp.service.name }}
              containerPort: {{ .Values.formsWebApp.config.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: {{.Values.formsWebApp.service.name }}
          readinessProbe:
            httpGet:
              path: /health
              port: {{.Values.formsWebApp.service.name }}
          env:
            - name: APPEALS_SERVICE_API_URL
              value: "http://{{ include "app.fullname" . }}:{{ .Values.appealsServiceApi.service.port }}"
            - name: DOCUMENTS_SERVICE_API_URL
              value: "http://{{ include "app.fullname" . }}:{{ .Values.documentServiceApi.service.port }}"
            - name: PDF_SERVICE_API_URL
              value: "http://{{ include "app.fullname" . }}:{{ .Values.pdfServiceApi.service.port }}"
            - name: GOOGLE_ANALYTICS_ID
              value: {{ .Values.formsWebApp.config.googleAnalyticsId | quote }}
            - name: FILE_UPLOAD_DEBUG
              value: {{ .Values.formsWebApp.config.upload.debug | quote }}
            - name: FILE_UPLOAD_MAX_FILE_SIZE_BYTES
              value: {{ .Values.documentServiceApi.config.upload.maxSize | quote }}
            - name: FILE_UPLOAD_TMP_PATH
              value: {{ .Values.formsWebApp.config.upload.uploadDir | quote }}
            - name: FILE_UPLOAD_USE_TEMP_FILES
              value: {{ .Values.formsWebApp.config.upload.useTmpFiles | quote }}
            - name: HOST_URL
              value: "http://{{ include "app.fullname" . }}:{{ .Values.formsWebApp.service.port }}"
            - name: LOGGER_LEVEL
              value: {{ .Values.formsWebApp.config.logLevel }}
            - name: PORT
              value: {{ .Values.formsWebApp.config.port | quote }}
            - name: SESSION_MONGODB_DB_NAME
              value: forms-web-app
            - name: SESSION_MONGODB_COLLECTION
              value: sessions
            - name: SESSION_MONGODB_URL
              valueFrom:
                secretKeyRef:
                  key: value
                  name: akv-mongodb-connection-url
            - name: SESSION_KEY
              valueFrom:
                secretKeyRef:
                  key: value
                  name: akv-fwa-session-key
            - name: SUBDOMAIN_OFFSET
              value: {{ .Values.formsWebApp.config.subdomainOffset | quote }}
            - name: USE_SECURE_SESSION_COOKIES
              value: "true"
            - name: GOOGLE_TAG_MANAGER_ID
              value: {{ .Values.formsWebApp.config.googleTagManagerId | quote }}
            - name: FEATURE_FLAG_GOOGLE_TAG_MANAGER
              value: {{ .Values.formsWebApp.config.featureFlagGoogleTagManager | quote }}
          volumeMounts:
            - mountPath: {{ .Values.formsWebApp.config.upload.uploadDir | quote }}
              name: upload-cache
          resources:
      {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: upload-cache
          emptyDir: {}
