name: Appeals Service API

env:
  APP_DIR: appeals-service-api
  APP_NAME: appeals-service-api
  RELEASE_BRANCH: master

defaults:
  run:
    working-directory: appeals-service-api

on:
  push:
    branches:
      - main
      - master
      - develop
      - 'feature/**'
      - 'fix/**'
    paths:
      - appeals-service-api/**/*

jobs:
  build:
    runs-on: ubuntu-latest
    if: "! contains(toJSON(github.event.commits.*.message), '[ci skip]')"
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - run: npm ci

      - name: Get next version number
        uses: ./.github/actions/semantic-release
        id: version_number
        with:
          DIR: ${{ env.APP_DIR }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GET_VERSION: 'true'

      - name: Extract variables
        id: vars
        run: |
          BRANCH=${GITHUB_REF#refs/heads/}
          echo "::set-output name=branch::$BRANCH"

          CLEAN_TAG=$(echo $BRANCH | tr "/" "-")
          DOCKER_TAG=$CLEAN_TAG
          [ "$CLEAN_TAG" == "$RELEASE_BRANCH" ] && DOCKER_TAG=latest

          echo "::set-output name=docker-tag::$DOCKER_TAG"

          NEW_RELEASE_VERSION=${{ steps.version_number.outputs.new_release_version_number }}
          [ "${{ steps.version_number.outputs.new_release_published }}" == "false" ] && NEW_RELEASE_VERSION="$DOCKER_TAG-dev"

          echo "::set-output name=new_version::$NEW_RELEASE_VERSION"

      - name: Next version
        run: echo ${{ steps.vars.outputs.new_version }}

      - run: npm run lint

      - run: npm test

      - run: npm run test:cov

      - name: Build common Docker image
        run: docker build -t common ../common

      - name: Build Docker tagged image
        uses: ./.github/actions/docker
        with:
          APP_DIR: ${{ env.APP_DIR }}
          APP_NAME: ${{ env.APP_NAME }}
          DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_TAG: ${{ steps.vars.outputs.docker-tag }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          VERSION: ${{ steps.vars.outputs.new_version }}

      - name: Build Docker versioned image
        uses: ./.github/actions/docker
        if: ${{ steps.version_number.outputs.new_release_published == 'true' }}
        with:
          APP_DIR: ${{ env.APP_DIR }}
          APP_NAME: ${{ env.APP_NAME }}
          DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_TAG: ${{ steps.version_number.outputs.new_release_version_number  }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          VERSION: ${{ steps.vars.outputs.new_version }}

      - uses: ./.github/actions/flux
        if: ${{ steps.version_number.outputs.new_release_published == 'true' }}

      - name: Set next version number
        uses: ./.github/actions/semantic-release
        if: ${{ steps.version_number.outputs.new_release_published == 'true' }}
        with:
          DIR: ${{ env.APP_DIR }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SET_VERSION: 'true'
